import Image from 'next/image'
import Link from 'next/link'
import styles from './about.module.css'

const flywheelSteps = [
  {
    label: '01',
    title: 'We Broker',
    copy:
      'We manage the end-to-end technical production and logistics for institutional print, signage, and apparel orders, reducing retail overhead for schools, ministries, and local businesses.',
  },
  {
    label: '02',
    title: 'We Fuel',
    copy:
      'The B2B margins generated by larger procurement contracts are redirected back into the Chrism ecosystem instead of being lost to fragmented vendors and inflated retail markups.',
  },
  {
    label: '03',
    title: 'We Subsidize',
    copy:
      'That capital helps deliver secure, high-quality digital coordination tools to local volunteer ministries for free or at a deeply subsidized cost.',
  },
]

const platformPillars = [
  {
    eyebrow: 'The Ministry OS',
    title: 'Chrism Software',
    copy:
      'A streamlined web interface built to erase administrative friction for parish ministries, lay leadership, and volunteer coordinators.',
    points: [
      'Move ministries away from chaotic spreadsheets and fragmented communication apps.',
      'Bring member directories, volunteer coordination, and event planning into one mobile-friendly environment.',
      'Remove the financial barrier to digital transformation with tools built to be free or deeply subsidized for local ministries.',
    ],
  },
  {
    eyebrow: 'Liturgical & Fundraising Supply',
    title: 'Chrism Commerce',
    copy:
      'Premium, high-quality print collateral that honors the dignity of the mission, with a dedicated alternative to generic mass-market options.',
    points: [
      'Equip councils and parish groups with traditionally folding Christmas card packages at wholesale cost.',
      'Support high-margin local fundraising rooted in sacred art and excellent production quality.',
      'Produce typographically refined sacramental certificates on heavyweight archival stocks with precise pre-press layouts.',
    ],
  },
  {
    eyebrow: 'Institutional Print Sourcing',
    title: 'Chrism Brokerage',
    copy:
      'A specialized commercial print procurement partner that uses a trade-only wholesale network to bypass standard retail markups.',
    points: [
      'Source parish bulletins, marketing postcards, large-format signs, administrative forms, custom apparel, and board-level RFQ print needs.',
      'Handle technical production details including CMYK color, vector layout scaling, and high-resolution output requirements.',
      'Use institutional print savings to sustain the broader chrism.app software ecosystem.',
    ],
  },
]

export default function AboutPage() {
  return (
    <main className="qv-page">
      <div className={`qv-shell ${styles.aboutShell}`}>
        <header className={styles.topBar}>
          <Link href="/" className={styles.brandLink} aria-label="Chrism home">
            <Image
              src="/Chrism_horiz.svg"
              alt="Chrism"
              width={419}
              height={98}
              priority
              className={styles.brandImage}
            />
          </Link>

          <Link href="/login" className={`qv-button-secondary qv-link-button ${styles.signInButton}`}>
            Launch the app
          </Link>
        </header>

        <section className={styles.heroBlock}>
          <div className={styles.heroTextBlock}>
            <p className={styles.eyebrow}>Mission & Ecosystem</p>
            <h1 className={styles.heroTitle}>Our Mission & The Chrism Ecosystem</h1>
            <p className={styles.heroLead}>
              Operationalizing solidarity and subsidiarity through high-performance technology and physical supply chains.
            </p>
          </div>

          <div className={styles.heroCard}>
            <p>
              Chrism bridges commercial enterprise and community stewardship so operational capital can stay closer to the
              ministries, schools, councils, and local organizations doing the work on the ground.
            </p>
          </div>
        </section>

        <section className={styles.visionGrid}>
          <div className={styles.imageColumn}>
            <div className={styles.imageFrame}>
              <Image
                src="/jonny-gios-QMesAlxmi6g-unsplash.jpg"
                alt="Large mural text reading you and me"
                fill
                className={styles.aboutImage}
                sizes="(max-width: 900px) 100vw, 38vw"
              />
            </div>
            <p className={styles.photoCredit}>
              Photo by{' '}
              <a
                href="https://unsplash.com/@supergios?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText"
                target="_blank"
                rel="noreferrer"
              >
                Jonny Gios
              </a>{' '}
              on{' '}
              <a
                href="https://unsplash.com/photos/a-black-and-white-sign-that-says-you-and-me-and-you-and-me-QMesAlxmi6g?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText"
                target="_blank"
                rel="noreferrer"
              >
                Unsplash
              </a>
            </p>
          </div>

          <section className={styles.contentCard}>
            <p className={styles.eyebrow}>The Vision</p>
            <h2 className={styles.sectionTitle}>The Vision behind Chrism</h2>
            <div className={styles.copyStack}>
              <p>
                Historically, faith-driven communities, families, educators, and leaders have been called to pursue excellence,
                support their neighbors, and navigate a highly competitive world. But too often, the administrative tools and
                physical collateral required to run a thriving community come with an unsustainable corporate tax: inflated
                retail print margins, bloated software contracts, and fragmented tech stacks.
              </p>
              <p>
                Chrism is a purpose-driven, closed-loop economic and technological ecosystem engineered to bridge the gap
                between commercial enterprise and community stewardship.
              </p>
              <p>
                By leveraging an advanced, high-volume commercial print-brokerage network, Chrism captures standard retail
                printing margins and redirects that capital inward. Commercial enterprise subsidizes elite management tools
                for local ministries, creates high-margin fundraising mechanisms for fraternal organizations, and reduces
                operational overhead for schools and local businesses.
              </p>
              <p className={styles.statement}>
                When the faith-based marketplace succeeds, the faith-based ministry directly thrives.
              </p>
            </div>
          </section>
        </section>

        <section className={styles.flywheelSection}>
          <div className={styles.sectionIntro}>
            <p className={styles.eyebrow}>The Flywheel</p>
            <h2 className={styles.sectionTitle}>How the Flywheel Works</h2>
            <p>
              Chrism does not operate like a traditional commercial vendor. It runs on a self-sustaining loop where physical
              commerce funds and accelerates digital infrastructure.
            </p>
          </div>

          <div className={styles.flywheelGrid}>
            {flywheelSteps.map((step) => (
              <article key={step.title} className={styles.stepCard}>
                <span className={styles.stepLabel}>{step.label}</span>
                <h3>{step.title}</h3>
                <p>{step.copy}</p>
              </article>
            ))}
          </div>
        </section>

        <section className={styles.platformSection}>
          <div className={styles.sectionIntroWide}>
            <p className={styles.eyebrow}>The Platform</p>
            <h2 className={styles.sectionTitle}>The Three Pillars of the Platform</h2>
          </div>

          <div className={styles.pillarGrid}>
            {platformPillars.map((pillar) => (
              <article key={pillar.title} className={styles.platformCard}>
                <p className={styles.pillarEyebrow}>{pillar.eyebrow}</p>
                <h3>{pillar.title}</h3>
                <p>{pillar.copy}</p>
                <ul>
                  {pillar.points.map((point) => (
                    <li key={point}>{point}</li>
                  ))}
                </ul>
              </article>
            ))}
          </div>
        </section>

        <section className={styles.trustBand}>
          <div>
            <p className={styles.eyebrow}>Trust & Security</p>
            <h2 className={styles.trustTitle}>Built for Trust & Security</h2>
          </div>
          <div className={styles.copyStack}>
            <p>
              Because Chrism bridges public procurement, ministry coordination, and community management, our infrastructure
              is built around practical enterprise standards. The ecosystem is operated through a secure Cloudflare network
              and configured with modern email authentication practices including SPF, DKIM, and DMARC.
            </p>
            <p>
              Chrism is an Ontario-registered sole proprietorship dedicated to keeping operational capital where it matters
              most: directly supporting your mission.
            </p>
          </div>
        </section>

        <section className={styles.ctaSection}>
          <p className={styles.eyebrow}>Next Step</p>
          <h2 className={styles.ctaTitle}>Ready to optimize your organization&apos;s ecosystem?</h2>
          <div className={styles.ctaActions}>
            <Link href="#brokerage" className="qv-link-button qv-button-secondary">
              Explore Our Sourcing Network
            </Link>
            <Link href="mailto:syd.fernandez@chrism.app?subject=Chrism%20comparison%20quote" className="qv-link-button qv-button-secondary">
              Get a Comparison Quote
            </Link>
            <Link href="/login" className="qv-link-button qv-button-primary">
              Launch the App
            </Link>
          </div>
        </section>
      </div>
    </main>
  )
}
