DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'app') THEN
    GRANT USAGE ON SCHEMA app TO service_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA app TO service_role;
    GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA app TO service_role;
    GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA app TO service_role;

    ALTER DEFAULT PRIVILEGES IN SCHEMA app
      GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO service_role;

    ALTER DEFAULT PRIVILEGES IN SCHEMA app
      GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO service_role;

    ALTER DEFAULT PRIVILEGES IN SCHEMA app
      GRANT EXECUTE ON FUNCTIONS TO service_role;
  END IF;
END
$$;
